name: Publish Lambda
on:
push:
  branches: main
  paths:
    - "lambdas/*"
    - ".github/workflows/lambda.yaml"

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.DEPLOY_AWS_ACCESS_KEY }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.DEPLOY_AWS_ACCESS_SECRET }}

jobs:
deploy:
  runs-on: ubuntu-20.04
  steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12.16.1
      uses: actions/setup-node@v1
      with:
        node-version: 12.16.1
    - name: install
      run: npm install
    - name: build
      run: npm run build:api
    - name: deploy
      run: npm run deploy:api
